### ISSUE TITLE
Not working for some demo models

### ISSUE THREAD

**Issue by justanhduc** [ThibaultCastells/minimalist_network_graph#1]
Hi. Thanks for open-sourcing this useful tools. I ran a quick demo using the provided scripts but seems like it doesn't work for the following models

- vgg_16_bn
- googlenet
- densenet_40

Could you please check again? Thanks. I'm using Pytorch 1.8.1 if it's important.

**Comment by ThibaultCastells** [comment]
Hello, those are the models working on CIFAR10 so I guess the issue is related to that.
First, did you specify the input size to be 32 with ```--input 32```?
If the answer is yes, could you show me the error message you get? For me, there is no issue.

**Comment by justanhduc** [comment]
Hi @ThibaultCastells. Indeed that was the problem. Thanks for pointing that out.
