### ISSUE TITLE
Showing input/output sizes of each op

### ISSUE THREAD

**Issue by justanhduc** [ThibaultCastells/minimalist_network_graph#2]
Hi. Thank you for publishing this useful tool. I think because it requires an input and tracing, the input/output shapes of each op can be recorded. So it will be more informative if that information is shown when hovering over each op in the drawing. Is it possible to include such info to the final drawing? Thanks a lot!

**Comment by ThibaultCastells** [comment]
Hello!
Yes, I think it is possible. It is a feature I'm already working on, actually. Stay tuned!

**Comment by ThibaultCastells** [comment]
And this is done! I close the issue.
